apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qianxue-test-lifeline-ns

metadata:
  name: qianxue-test-lifeline
  namespace: qianxue-test-lifeline-ns

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml
- env-configmap.yaml
- hpa.yaml

images:
- name: omaticaya/qianxue-test-lifeline
  newTag: 1.0.1

commonLabels:
  app: qianxue-test-lifeline
  managed-by: argocd


